### ISSUE TITLE
python3 manage.py时报错

### ISSUE THREAD

**Issue by ne1000** [cucker0/BindUI#2]
报错：django.core.exceptions.ImproperlyConfigured: mysqlclient 1.4.0 or newer is required; you have 0.10.0.

以下文件都加入了
import pymysql
pymysql.install_as_MySQLdb()

./DnsRecord/migrations/__init__.py
./DnsRecord/templatetags/__init__.py
./DnsRecord/__init__.py
./authentication/migrations/__init__.py
./authentication/__init__.py
./bindUI/__init__.py

但还是不行

**Comment by cucker0** [comment]
已在 release-2.0 版本修复该问题。处理方法：

./bindUI/settings.py 添加下面的配置
```bash
import pymysql
# 指定 pymysql 的版本。主要是要比 Django 要求的最低版本要大
pymysql.version_info = (11, 1, 0, "final", 0)
pymysql.install_as_MySQLdb()
```
